### ISSUE TITLE
Issues Loading Designer-Shop for EU vs. NA?

### ISSUE THREAD

**Issue by artpolitic** [spreadshirt/apps#8] opened 2016-01-08 09:50 UTC
Hi,

I've been trying to embed the Tablomat into my website and for testing purposes I simply used the sample code and put it into a local html file on my desktop. When I test it with one of my shop IDs for the NA platform, it always works properly and loads all available marketplace designs.

However, when I do this for a designer shop on the EU platform, it doesn't work. The Tablomat loads and I can even load specific products, but the marketplace designs never show. Not even my own. I've tested it with multiple accounts and I've also test the shop via the direct link on the Spreadshirt server (it works there).

Any idea what the issue might be?

UPDATE:
It seems this only happens to me when I used Chrome as a browser and when I'm trying to load an EU shop. With MSIE it works fine, which I find odd.

Regards
artpolitic

**Comment by it-ony** [comment] 2016-01-08 13:25
Hi, 

the problem sounds strange. Can you please post the example code you haved used for EU in chrome.

Thanks,
Tony

**Comment by artpolitic** [comment] 2016-01-08 13:50
I know it's strange. Here's the code I'm using:

```html
<html>
<head>
</head>
<body>

<div id="tablomatContainer"></div>

<script type="text/javascript">
	window.spreadshirtLoaded = window.spreadshirtLoaded || [];
	window.spreadshirtLoaded.push(function(spreadshirt) {
		// invoked when the spreadshirt library is loaded
		spreadshirt.create("tablomat", {
			target: document.getElementById("tablomatContainer"),
			shopId: 503780,
			platform: "EU",
			mode: "partner"
		});
	});
</script>
<script type="text/javascript" src="http://spreadshirt.github.io/apps/spreadshirt.min.js"></script>

</body>
</html>
```

Here's an example of the results I get:
http://postimg.org/image/vy3ptgxa5/

This actually happens to me with your main example as well, when I open it with Chrome:
http://spreadshirt.github.io/apps/

Cheers
Christian

**Comment by it-ony** [comment] 2016-01-08 15:30
Hi, 

we identified the problem due to an API change some time ago. Right now the behavior depends on the language of the browser. The language of the browser plus the platform specified will map to an locale, which might be invalid.

So, I guess in your chrome browser you'll have a language different from de-*, that's why the script generates a locale which is e.g. en_DE (DE is fixed for EU platform) resulting in not showing any design.

Next week we're planning for a release, where we can fix this issue.

Tony

**Comment by artpolitic** [comment] 2016-01-08 15:36
Hi Tony,

indeed, the platform would probably be mapping to DE, while my browser uses English. But wouldn't that happen with IE as well?

Regards
Christian

**Comment by it-ony** [comment] 2016-01-08 15:39
Sure.

If you need a working embed script right now, I can extend the script with two parameters allowing to set the language and country by your own. But this won't work for existing implementations without specifying those parameters.

That's why the more general approach is now to fix the root cause of the api change and then use the locale of the shop.

Tony

**Comment by artpolitic** [comment] 2016-01-08 16:26
Hi Tony,

no it's fine, no rush. I can wait for the planned release.

I was just wondering why the issue didn't happen with me when using IE, even though the same preconditions are given as with Chrome. Both browsers are on an English locale.

Regards
Chris

**Comment by it-ony** [comment] 2016-01-08 16:29
You can open up IE and try to find a js console :)
Then type `window.navigator.language` and post the result.

**Comment by artpolitic** [comment] 2016-01-11 08:30
Hi Tony,

I had to wait until I got back to the office, since I don't have IE back home (Mac).

I tested both cases and got the following results:
- Chrome: en-US
- IE: de-DE

So I guess you were right, although I'm not entirely sure why IE is showing up the way it is ;)

**Comment by it-ony** [comment] 2016-01-13 12:26
Should be fixed with the release today. Please give feedback.

**Closed by it-ony** 2016-01-13 12:26 UTC

**Comment by artpolitic** [comment] 2016-01-13 13:35
Works like a charm! :)
